### ISSUE TITLE
Web app unresponsive

### ISSUE THREAD

**Issue by younkim** [zauberzeug/odrive-gui#1]
There seems to be some issues with the web app in your Docker image/`main.py`. A couple things:

- According to NiceGUI's doc, default port is 8080, and `ui.run()` doesn't set a port here, so the Docker CLI command should probably use `-p 80:8080`
- Trying to access the app at `http://localhost` is still unsuccessful. No server response code (unreachable).

`docker run --rm --privileged -p 80:8080 --name odrive -it zauberzeug/odrive-gui:latest` prints the following:

```
/usr/local/lib/python3.9/site-packages/justpy
Module directory: /usr/local/lib/python3.9/site-packages/justpy, Application directory: /app
```

Any idea? @zauberzeug-dev

**Comment by rodja** [comment]
@younkim sorry for the late reply. Until now we have simply called `odrive.find_any` before serving the web ui. This function blocks indefinitely if it does not find an connected odrive. I think this is the most likely cause for the situation you described.
I've just created a new release which better shows the status of the connection process. Please give it a try. And make sure the odrive is correctly connected via usb.

**Comment by falkoschindler** [comment]
I'll close this issue for now. Feel free to create a new one if the problem persists with a new version of ODrive GUI.
