### ISSUE TITLE
0.5.1   v3.6  can  use  this  gui?

### ISSUE THREAD

**Issue by zouzhe1** [zauberzeug/odrive-gui#2]
0.5.1   v3.6  can  use  this  gui?

**Comment by rodja** [comment]
I'm sorry. Could you explain a bit more? Do you ask about Python 3.6 compatibility?

**Comment by zouzhe1** [comment]
@rodja no python3.6,it is odrive PCB V3.6 56V

**Comment by rodja** [comment]
Should work. Have you tried it?

**Comment by dreusel** [comment]
It works fine for me with 3.6 hardware and 0.5.1 firmware. Just the 'dump errors' feature doesn't work. Not sure if that's specific to the the 0.5.1 firmware, I haven't tried it with any other version.

**Comment by rodja** [comment]
I'll close this issue for now. Feel free to create another, more specific one.
